# Generated by scripts/release.py (release-kit) from the v2026.9.2 release — do not edit.
class Bx < Formula
  desc "Run binaries from GitHub releases. npx for compiled tools, with MCP-server smarts"
  homepage "https://github.com/grahambrooks/bx"
  version "2026.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.9.2/bx-v2026.9.2-aarch64-apple-darwin.tar.gz"
      sha256 "d8d0b1001b5d89ea9de74ed9df612a441695cb013d605a7d5ac246d66119786f"
    end
    on_intel do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.9.2/bx-v2026.9.2-x86_64-apple-darwin.tar.gz"
      sha256 "df8b1be0d6b22669765ca493d89228f3dc4ed5940562a094759d7ef00cad7e72"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.9.2/bx-v2026.9.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "54495a642a4492595c99691a294c641e183c654f052d6a50be4a2e3a5afa2302"
    end
    on_intel do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.9.2/bx-v2026.9.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "40294656d5b94ade52cb492b85d5f128c2b6e88ac1d32286ef779b3fd9e06703"
    end
  end

  def install
    bin.install "bx"
  end

  test do
    assert_path_exists bin/"bx"
  end
end
