# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Bx < Formula
  desc "Run binaries from GitHub releases. npx for compiled tools, with MCP-server smarts"
  homepage "https://github.com/grahambrooks/bx"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.10.1/bx-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "9dfd5f4667a62ac68cbee9f107eee07143aa46199080335a5d3fc36b62798b59"
    end
    on_intel do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.10.1/bx-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "117c881a9de1e4555fb8281b74b7b02ebe6baf189d48dc5c0529c56b6ddc0b4f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.10.1/bx-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "50578128f10fae42829383bacbdda4c5a3387e53ea6699618e4e6cf3b7e46a14"
    end
    on_intel do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.10.1/bx-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "156e0d40c44b919fc315cd2a7fb5ed7a514cbd41fc47d357bef2461288cb5922"
    end
  end

  def install
    bin.install "bx"
  end

  test do
    assert_path_exists bin/"bx"
  end
end
