# Generated by scripts/release.py (release-kit) from the v2026.9.3 release — do not edit.
class Bx < Formula
  desc "Run binaries from GitHub releases. npx for compiled tools, with MCP-server smarts"
  homepage "https://github.com/grahambrooks/bx"
  version "2026.9.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.9.3/bx-v2026.9.3-aarch64-apple-darwin.tar.gz"
      sha256 "130a0bcea9598a3622232af2139912fd92fd5502d5174db05a1ceb2522f9b42e"
    end
    on_intel do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.9.3/bx-v2026.9.3-x86_64-apple-darwin.tar.gz"
      sha256 "e88bcf75c751edfa25ac84bb5355d6579170e241ccac5e2e649698c8b0816940"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.9.3/bx-v2026.9.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9031bc311f3577769d7321c5143296bb31dba80bb4c9ad1522ef93ade158f092"
    end
    on_intel do
      url "https://github.com/grahambrooks/bx/releases/download/v2026.9.3/bx-v2026.9.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6a542ded3afb210b91777a56a526acb491beebdef0584db25fd096c00a3f9f55"
    end
  end

  def install
    bin.install "bx"
  end

  test do
    assert_path_exists bin/"bx"
  end
end
